### ISSUE TITLE
Add Monochrome Icon

### ISSUE THREAD

**Issue by klassenserver7b** [Vertretungsapp/app#143]

**Comment by klassenserver7b** [comment]
Probably we have to wait until this (capacitor/assets issue)[https://github.com/ionic-team/capacitor-assets/issues/428] gets resolved

**Comment by SachsenspieltCoding** [comment]
Hey @klassenserver7b, I completely overlooked your issue. I am so sorry.
Do you mean the Android App Icon of the APK version?

> [!NOTE]
> You're probably referencing the main branch. Currently I am working on a complete recode (see branches), to make the app more stable and robust for upcomming 1.0 (just FYI)

**Comment by klassenserver7b** [comment]
Yes i mean the App Icon of the APK Version.
For me it looks really shitty to have all icons but this app in monochrome xD

**Comment by SachsenspieltCoding** [comment]
> Yes i mean the App Icon of the APK Version.
> 
> For me it looks really shitty to have all icons but this app in monochrome xD

Well, I can understand you.
Actually I didn't really familiarise with the Android development nor the correct theming of those things. The APK version is/was more like a technical demonstration than a fully supported app.

But I hear you out and I will note that for the upcoming recode, if there will be a capacitor (or similar) build again.

**Comment by SachsenspieltCoding** [comment]
@klassenserver7b 
I have a question regarding the monochrome icons: since you may be a bit more of an expert on this topic, how should I make a monochrome icon? Could you please give me some instructions or references? I'm completely new to this.

The current icons of the (re)recode are as following:

`icon.png`
![icon](https://github.com/Vertretungsapp/app/assets/59836848/265e1427-b9e8-46d5-8cc9-472df7687525)

`adaptive-icon.png`
![adaptive-icon](https://github.com/Vertretungsapp/app/assets/59836848/203b9e04-27d1-4f72-b429-793a560da776)

`favicon.png`
![favicon](https://github.com/Vertretungsapp/app/assets/59836848/7946f5a5-3a1e-4232-ac0b-6b1bd8d178d6)

**Comment by klassenserver7b** [comment]
basicly is that what you need: [https://developer.android.com/develop/ui/views/launch/icon_design_adaptive](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive)
The best is when you have one color for your Logo ("VP.") and the backgroud is translucent

**Comment by SachsenspieltCoding** [comment]
Thanks, I will look into it.

But since the future of the app is currently unsure, due to Apple killing PWAs in the EU, I won't touch it in the closet future. Sorry for that

**Comment by SachsenspieltCoding** [comment]
Hey @klassenserver7b,
since the Android Version isn't supported since 1.0 anymore, I'll close this issue. I am sorry for that.
If you have any other questions or bugs, feel free to create a new issue :)
